use iii_skill_core::source_map::{candidates, translate};
use std::path::{Path, PathBuf};

// --- candidates -----------------------------------------------------------

#[test]
fn candidates_docs_mode_mdx_to_source() {
    let cands = candidates(Path::new("docs/foo.mdx.skill.md"));
    assert_eq!(cands, vec![PathBuf::from("docs/foo.mdx")]);
}

#[test]
fn candidates_docs_mode_md_to_source() {
    let cands = candidates(Path::new("docs/reference/cli.md.skill.md"));
    assert_eq!(cands, vec![PathBuf::from("docs/reference/cli.md")]);
}

#[test]
fn candidates_worker_leaf_to_source() {
    let cands = candidates(Path::new("queues/skills/dequeue.md"));
    assert_eq!(
        cands,
        vec![PathBuf::from("queues/docs/leaves/dequeue.md")]
    );
}

#[test]
fn candidates_worker_readme_returns_partials_in_render_order() {
    // README.md is composed from docs/{intro,quickstart,companions}.md
    // plus docs/leaves/*. Gated on the parent dir actually being a
    // worker (has docs/intro.md), so we set that up.
    let tmp = tempfile::tempdir().unwrap();
    let worker = tmp.path().join("queues");
    std::fs::create_dir_all(worker.join("docs")).unwrap();
    std::fs::write(worker.join("docs").join("intro.md"), "").unwrap();

    let cands = candidates(&worker.join("README.md"));
    assert_eq!(
        cands.iter().take(3).cloned().collect::<Vec<_>>(),
        vec![
            worker.join("docs").join("intro.md"),
            worker.join("docs").join("quickstart.md"),
            worker.join("docs").join("companions.md"),
        ]
    );
}

#[test]
fn candidates_worker_skill_md_same_partial_set_as_readme() {
    let tmp = tempfile::tempdir().unwrap();
    let worker = tmp.path().join("queues");
    std::fs::create_dir_all(worker.join("docs")).unwrap();
    std::fs::write(worker.join("docs").join("intro.md"), "").unwrap();

    let r = candidates(&worker.join("README.md"));
    let s = candidates(&worker.join("skill.md"));
    assert_eq!(r, s);
}

#[test]
fn candidates_root_readme_not_treated_as_worker() {
    // The repo's top-level README.md must not be misidentified as a
    // worker README and remapped to a non-existent docs/intro.md.
    let tmp = tempfile::tempdir().unwrap();
    let readme = tmp.path().join("README.md");
    std::fs::write(&readme, "# top-level readme\n").unwrap();
    // No iii.worker.yaml, no docs/intro.md sibling.
    let cands = candidates(&readme);
    assert!(
        cands.is_empty(),
        "root-level README should have no candidates, got {cands:?}"
    );
}

#[test]
fn candidates_unknown_path_returns_empty() {
    let cands = candidates(Path::new("some/random/file.md"));
    assert!(cands.is_empty());
}

// --- translate ------------------------------------------------------------

#[test]
fn translate_docs_mode_finds_matching_source_line() {
    let tmp = tempfile::tempdir().unwrap();
    let docs = tmp.path().join("docs");
    std::fs::create_dir_all(&docs).unwrap();

    let src = docs.join("foo.mdx");
    std::fs::write(
        &src,
        "---\ntitle: Foo\n---\n\n# Foo\n\nThe unique source line.\nA second prose line.\n",
    )
    .unwrap();

    let rendered = docs.join("foo.mdx.skill.md");
    // Renderer typically strips frontmatter; mimic that — body lines shift up.
    std::fs::write(
        &rendered,
        "# Foo\n\nThe unique source line.\nA second prose line.\n",
    )
    .unwrap();

    // Line 3 of the rendered file is "The unique source line."
    let result = translate(&rendered, 3);
    let (path, line) = result.expect("docs mode should produce a candidate");
    assert_eq!(path, src);
    // Source line is offset by the stripped frontmatter (4 lines).
    assert_eq!(line, 7, "expected source line 7, got {line}");
}

#[test]
fn translate_worker_leaf_finds_matching_source_line() {
    let tmp = tempfile::tempdir().unwrap();
    let worker = tmp.path().join("queues");
    let leaves = worker.join("docs").join("leaves");
    let skills = worker.join("skills");
    std::fs::create_dir_all(&leaves).unwrap();
    std::fs::create_dir_all(&skills).unwrap();

    let src = leaves.join("dequeue.md");
    std::fs::write(
        &src,
        "# Pulling from a topic\n\n- Anchor line that should round-trip.\n- Other notes.\n",
    )
    .unwrap();

    let rendered = skills.join("dequeue.md");
    // Renderer prepends a "generated by" header.
    std::fs::write(
        &rendered,
        "<!-- generated by iii-skill-render. DO NOT EDIT. -->\n\n# Pulling from a topic\n\n- Anchor line that should round-trip.\n- Other notes.\n",
    )
    .unwrap();

    // Line 5 of rendered is "- Anchor line that should round-trip."
    let (path, line) = translate(&rendered, 5).expect("worker leaf should map");
    assert_eq!(path, src);
    assert_eq!(line, 3, "expected source line 3, got {line}");
}

#[test]
fn translate_worker_readme_finds_correct_partial() {
    let tmp = tempfile::tempdir().unwrap();
    let worker = tmp.path().join("queues");
    let docs = worker.join("docs");
    std::fs::create_dir_all(&docs).unwrap();

    std::fs::write(
        docs.join("intro.md"),
        "Intro paragraph that only appears in intro.\n",
    )
    .unwrap();
    std::fs::write(
        docs.join("quickstart.md"),
        "# Quickstart\n\nA distinctive quickstart sentence that only lives here.\n",
    )
    .unwrap();
    std::fs::write(
        docs.join("companions.md"),
        "Companions blurb.\n",
    )
    .unwrap();

    let readme = worker.join("README.md");
    std::fs::write(
        &readme,
        "Intro paragraph that only appears in intro.\n\n# Quickstart\n\nA distinctive quickstart sentence that only lives here.\n\nCompanions blurb.\n",
    )
    .unwrap();

    // Rendered line 5 → "A distinctive quickstart sentence that only lives here."
    // That line lives in quickstart.md at line 3.
    let (path, line) = translate(&readme, 5).expect("worker README should map");
    assert_eq!(path, docs.join("quickstart.md"));
    assert_eq!(line, 3);
}

#[test]
fn translate_blank_line_returns_first_candidate_with_rendered_line() {
    let tmp = tempfile::tempdir().unwrap();
    let docs = tmp.path().join("docs");
    std::fs::create_dir_all(&docs).unwrap();
    let src = docs.join("foo.mdx");
    std::fs::write(&src, "# Foo\n\nNot blank.\n").unwrap();
    let rendered = docs.join("foo.mdx.skill.md");
    std::fs::write(&rendered, "# Foo\n\nNot blank.\n").unwrap();

    // Line 2 is blank — too ambiguous to anchor. Return the source path
    // with the rendered line as a best-effort scan anchor.
    let (path, line) = translate(&rendered, 2).expect("should still surface source");
    assert_eq!(path, src);
    assert_eq!(line, 2);
}

#[test]
fn translate_no_match_falls_back_to_first_candidate() {
    let tmp = tempfile::tempdir().unwrap();
    let docs = tmp.path().join("docs");
    std::fs::create_dir_all(&docs).unwrap();
    let src = docs.join("foo.mdx");
    std::fs::write(&src, "# Source-only content.\n").unwrap();
    let rendered = docs.join("foo.mdx.skill.md");
    // Rendered has a line the source doesn't contain (e.g., renderer-inserted header).
    std::fs::write(
        &rendered,
        "<!-- generated header line that has no source -->\n# Source-only content.\n",
    )
    .unwrap();

    // Line 1 of rendered doesn't appear in source. Fall back to the source
    // path with the rendered line.
    let (path, line) = translate(&rendered, 1).expect("should fall back");
    assert_eq!(path, src);
    assert_eq!(line, 1);
}

#[test]
fn translate_unknown_pattern_returns_none() {
    let tmp = tempfile::tempdir().unwrap();
    let f = tmp.path().join("random.md");
    std::fs::write(&f, "content\n").unwrap();
    assert!(translate(&f, 1).is_none());
}
