use anyhow::Context;
use serde::Deserialize;
use std::path::Path;

/// Narrative-relevant fields from a worker's `iii.worker.yaml`.
///
/// `name` is required. `description` and `tags` are the searchable frontmatter
/// the renderer emits into `README.md` / `skill.md`; both are optional —
/// when absent (or empty) the renderer omits them from the frontmatter and
/// the structure layer emits a warning rather than failing the build.
///
/// API surface (function ids, signatures, descriptions, custom trigger payloads,
/// config schema) is auto-generated by a different system and is intentionally
/// not represented here.
#[derive(Debug, Deserialize)]
pub struct WorkerManifest {
    pub name: String,
    #[serde(default)]
    pub description: Option<String>,
    /// Comma-separated tags for search indexing, e.g. `"database, mysql"`.
    /// Emitted verbatim into the frontmatter `tags` field when present.
    #[serde(default)]
    pub tags: Option<String>,
}

impl WorkerManifest {
    /// `description` if present and non-blank, else `None`. Blank strings are
    /// treated as absent so an empty `description:` line is omitted + warned.
    pub fn description(&self) -> Option<&str> {
        self.description.as_deref().map(str::trim).filter(|s| !s.is_empty())
    }

    /// `tags` if present and non-blank, else `None`.
    pub fn tags(&self) -> Option<&str> {
        self.tags.as_deref().map(str::trim).filter(|s| !s.is_empty())
    }
}

/// Parse `<dir>/iii.worker.yaml` into the narrative subset. Errors only when
/// the file is unreadable, the YAML is malformed, or `name` is missing/empty.
/// Missing `description` / `tags` are tolerated here (warned at the structure
/// layer) so a render never fails on absent metadata.
pub fn read_manifest(dir: &Path) -> anyhow::Result<WorkerManifest> {
    let path = dir.join("iii.worker.yaml");
    let content = std::fs::read_to_string(&path)
        .with_context(|| format!("reading {}", path.display()))?;
    let manifest: WorkerManifest = serde_yaml::from_str(&content)
        .with_context(|| format!("parsing {}", path.display()))?;
    if manifest.name.trim().is_empty() {
        anyhow::bail!("{}: `name` must not be empty", path.display());
    }
    Ok(manifest)
}
