use anyhow::Context;
use serde::Deserialize;
use std::path::Path;

/// Narrative-relevant fields from a worker's `iii.worker.yaml`.
///
/// `name`, `description`, and `tags` are the searchable frontmatter the
/// renderer emits into `README.md` / `skill.md`; all three are required.
///
/// API surface (function ids, signatures, descriptions, custom trigger payloads,
/// config schema) is auto-generated by a different system and is intentionally
/// not represented here.
#[derive(Debug, Deserialize)]
pub struct WorkerManifest {
    pub name: String,
    pub description: String,
    /// Comma-separated tags for search indexing, e.g. `"database, mysql"`.
    /// Emitted verbatim into the frontmatter `tags` field.
    pub tags: String,
}

/// Parse `<dir>/iii.worker.yaml` into the narrative subset. Errors when any
/// required field (`name`, `description`, `tags`) is missing or empty.
pub fn read_manifest(dir: &Path) -> anyhow::Result<WorkerManifest> {
    let path = dir.join("iii.worker.yaml");
    let content = std::fs::read_to_string(&path)
        .with_context(|| format!("reading {}", path.display()))?;
    let manifest: WorkerManifest = serde_yaml::from_str(&content)
        .with_context(|| format!("parsing {} (need name, description, tags)", path.display()))?;
    if manifest.name.trim().is_empty() {
        anyhow::bail!("{}: `name` must not be empty", path.display());
    }
    if manifest.description.trim().is_empty() {
        anyhow::bail!("{}: `description` must not be empty", path.display());
    }
    if manifest.tags.trim().is_empty() {
        anyhow::bail!("{}: `tags` must not be empty", path.display());
    }
    Ok(manifest)
}
