//! Render a docs-mode source file into a `<source>.skill.md` artifact.
//!
//! Steps, in order:
//!   1. Parse + strip frontmatter via [`super::frontmatter::parse`].
//!   2. Detect file-level section default + the first doc-scope marker.
//!   3. Walk the body section by section (each `#`/`##`/`###`/... heading
//!      starts a new section); honour per-heading include/exclude markers
//!      to keep or drop each section's body.
//!   4. Strip every recognised `skill:` marker line from the output.
//!   5. Run the body through [`crate::llm_only::unwrap_llm_only`] so AI-only
//!      content is exposed in the skill artifact.
//!   6. Emit a generated-file header, the original frontmatter title as an
//!      H1 (if the body has none), and the kept content.

use crate::docs::frontmatter::{parse, Frontmatter, ParsedDoc};
use crate::docs::markers::{
    is_marker_line, parse_section_override, scan_section_default, strip_section_override,
    SectionDefault, SectionOverride,
};
use crate::human_only::strip_human_only;
use crate::llm_only::{strip_llm_only, unwrap_llm_only};
use std::path::Path;

/// Output of rendering one doc.
#[derive(Debug)]
pub struct RenderedSkill {
    /// The full skill body including the generated-file header.
    pub body: String,
    /// The doc's frontmatter, exposed so callers (vale, ai) can do
    /// type-aware checks without re-parsing.
    pub frontmatter: Frontmatter,
}

/// How llm-only content is handled at render time. Two views of the same
/// source produce two different artifacts.
#[derive(Debug, Clone, Copy)]
pub enum LlmOnlyMode {
    /// Consumer view (default). `llm-only:start...end` markers are
    /// stripped but the inner body stays, inline `llm-only: note`
    /// expands to its payload. The artifact LLM consumers (skillkit,
    /// agents reading `iii://`) see all the maintainer-targeted prose.
    Unwrap,
    /// Validator view. `llm-only:start...end` blocks are dropped
    /// entirely (markers and body), inline `llm-only: note` lines are
    /// dropped. This produces the "what would a human reader actually
    /// see" view used by `iii-skill-check` to validate against rules
    /// that only apply to reader-facing content (e.g., the AI judge's
    /// "no maintainer instructions in published docs" rule).
    Strip,
}

/// Render a single docs source file by path. Produces the consumer view
/// (llm-only content unwrapped). Use [`render_doc_with_mode`] when you
/// need the validator view.
pub fn render_doc(path: &Path) -> anyhow::Result<RenderedSkill> {
    render_doc_with_mode(path, LlmOnlyMode::Unwrap)
}

/// Render a single docs source file with explicit llm-only handling.
pub fn render_doc_with_mode(path: &Path, mode: LlmOnlyMode) -> anyhow::Result<RenderedSkill> {
    let content = std::fs::read_to_string(path)
        .map_err(|e| anyhow::anyhow!("reading {}: {e}", path.display()))?;
    render_str_with_mode(&content, path, mode)
}

/// Render docs content already in memory. Useful for tests and for the
/// drift check, which needs to compare in-memory output to on-disk output.
/// Produces the consumer view; use [`render_str_with_mode`] for the
/// validator view.
pub fn render_str(content: &str, source_path: &Path) -> anyhow::Result<RenderedSkill> {
    render_str_with_mode(content, source_path, LlmOnlyMode::Unwrap)
}

/// Render docs content with explicit llm-only handling.
pub fn render_str_with_mode(
    content: &str,
    source_path: &Path,
    mode: LlmOnlyMode,
) -> anyhow::Result<RenderedSkill> {
    let ParsedDoc { frontmatter, body } = parse(content)?;
    let default = scan_section_default(&body);
    let kept = filter_sections(&body, default);
    let stripped: String = kept
        .lines()
        .filter(|line| !is_marker_line(line))
        .map(|line| {
            // Heading lines may have trailing skill:section markers — drop the
            // markers but keep the heading text.
            if is_heading_line(line) {
                strip_section_override(line)
            } else {
                line.to_string()
            }
        })
        .collect::<Vec<_>>()
        .join("\n");
    let human_stripped = strip_human_only(&stripped);
    let processed = match mode {
        LlmOnlyMode::Unwrap => unwrap_llm_only(&human_stripped),
        LlmOnlyMode::Strip => strip_llm_only(&human_stripped),
    };

    let header = format!(
        "<!-- generated by iii-skill-render. DO NOT EDIT (changes here are overwritten on the next render). Edit {}. -->",
        source_path.display()
    );

    let needs_h1 = !has_h1(&processed);
    let mut sections: Vec<String> = vec![header];
    if needs_h1 {
        sections.push(format!("# {}", frontmatter.title));
    }
    let trimmed_body = processed.trim_end_matches('\n').to_string();
    if !trimmed_body.is_empty() {
        sections.push(trimmed_body);
    }
    let body = sections.join("\n\n") + "\n";

    Ok(RenderedSkill { body, frontmatter })
}

/// Walk the body by heading and drop sections whose effective inclusion
/// resolves to "exclude". A section runs from one heading line up to (but
/// not including) the next heading line; pre-heading content is treated
/// as the implicit "lead" section governed by the file-level default.
fn filter_sections(body: &str, default: SectionDefault) -> String {
    let lines: Vec<&str> = body.lines().collect();

    // Identify each heading's range and effective include/exclude state.
    let mut output: Vec<String> = Vec::new();
    let lead_included = match default {
        SectionDefault::IncludeByDefault => true,
        SectionDefault::ExcludeByDefault => false,
    };

    // Lead section: pre-first-heading content. Honours the default but the
    // "section override" markers inside the lead can flip it (rare but
    // useful when a file has a long preface that should be excluded).
    let lead_end = lines.iter().position(|l| is_heading_line(l)).unwrap_or(lines.len());
    let lead_override = lines[..lead_end]
        .iter()
        .find_map(|l| parse_section_override(l));
    let lead_keep = match lead_override {
        Some(SectionOverride::Include) => true,
        Some(SectionOverride::Exclude) => false,
        None => lead_included,
    };
    if lead_keep {
        for line in &lines[..lead_end] {
            output.push((*line).to_string());
        }
    }
    let mut i = lead_end;

    while i < lines.len() {
        let header_line = lines[i];
        // Advance to the next heading.
        let next = lines[i + 1..]
            .iter()
            .position(|l| is_heading_line(l))
            .map(|p| i + 1 + p)
            .unwrap_or(lines.len());

        // Section spans [i, next).
        let section_lines = &lines[i..next];
        let section_override = section_lines
            .iter()
            .find_map(|l| parse_section_override(l));
        let keep = match section_override {
            Some(SectionOverride::Include) => true,
            Some(SectionOverride::Exclude) => false,
            None => match default {
                SectionDefault::IncludeByDefault => true,
                SectionDefault::ExcludeByDefault => false,
            },
        };
        if keep {
            for line in section_lines {
                output.push((*line).to_string());
            }
        }
        i = next;

        // Suppress unused-warning when no heading lines exist.
        let _ = header_line;
    }

    output.join("\n")
}

fn is_heading_line(line: &str) -> bool {
    let t = line.trim_start();
    t.starts_with("# ")
        || t.starts_with("## ")
        || t.starts_with("### ")
        || t.starts_with("#### ")
        || t.starts_with("##### ")
        || t.starts_with("###### ")
}

fn has_h1(content: &str) -> bool {
    content
        .lines()
        .any(|line| line.trim_start().starts_with("# "))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn render_input(input: &str) -> String {
        render_str(input, &PathBuf::from("docs/example.mdx"))
            .expect("render should succeed")
            .body
    }

    #[test]
    fn renders_minimal_doc_with_default_include() {
        let input = "---\ntitle: Hello\ndescription: A doc\ntype: how-to\n---\n\n# Hello\n\nBody.\n";
        let out = render_input(input);
        assert!(out.contains("# Hello"));
        assert!(out.contains("Body."));
        assert!(out.contains("DO NOT EDIT"));
        assert!(out.contains("docs/example.mdx"));
    }

    #[test]
    fn injects_h1_from_frontmatter_when_body_has_none() {
        let input = "---\ntitle: Synthesised Title\ndescription: d\ntype: reference\n---\n\nNo H1 in body.\n";
        let out = render_input(input);
        assert!(out.contains("# Synthesised Title"));
    }

    #[test]
    fn excludes_section_when_marker_present() {
        let input = "---\ntitle: t\ndescription: d\ntype: how-to\n---\n\n# Top\n\nKeep this.\n\n## Internals <!-- skill:exclude-section -->\n\nDrop this.\n\n## Public\n\nKeep this too.\n";
        let out = render_input(input);
        assert!(out.contains("Keep this."));
        assert!(out.contains("Keep this too."));
        assert!(!out.contains("Drop this."));
        // The marker text itself is gone.
        assert!(!out.contains("skill:exclude-section"));
        // The heading stayed but without its marker.
        assert!(!out.contains("## Internals"));
    }

    #[test]
    fn exclude_by_default_then_include_specific_sections() {
        let input = "---\ntitle: t\ndescription: d\ntype: reference\n---\n<!-- skill:exclude-sections-by-default -->\n\n# Title\n\nLead text.\n\n## Public <!-- skill:include-section -->\n\nIn the skill.\n\n## Private\n\nNot in the skill.\n";
        let out = render_input(input);
        assert!(out.contains("In the skill."));
        assert!(!out.contains("Not in the skill."));
        // The lead "Title" section was excluded by default.
        assert!(!out.contains("Lead text."));
    }

    #[test]
    fn llm_only_blocks_unwrapped_in_kept_sections() {
        let input = "---\ntitle: t\ndescription: d\ntype: how-to\n---\n\n# Top\n\nVisible.\n\n<!-- llm-only:start -->\nFor the AI.\n<!-- llm-only:end -->\n";
        let out = render_input(input);
        assert!(out.contains("Visible."));
        assert!(out.contains("For the AI."));
        assert!(!out.contains("llm-only:start"));
    }

    #[test]
    fn marker_lines_are_dropped() {
        let input = "---\ntitle: t\ndescription: d\ntype: how-to\n---\n<!-- skill:include-sections-by-default -->\n\n# Top\n\nBody.\n";
        let out = render_input(input);
        assert!(!out.contains("skill:include-sections-by-default"));
    }
}
